initdbScripts:
  postgis-init.sql: |
    CREATE EXTENSION IF NOT EXISTS postgis;

persistence:
  enabled: true

postgresql:
  resources:
    requests:
      memory: "256Mi"
      cpu: "100m"
    limits:
      memory: "512Mi"
      cpu: "200m"
