name: Deploy to testing environment

on:
  push:
    branches:
      - "*/*"
  workflow_dispatch:

jobs:
  pdok_charting:
    name: Deploy pdok-charting
    runs-on: ubuntu-latest
    environment: testing
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to container registry
        run: docker login ghcr.io -p ${{ secrets.GH_TOKEN }} -u ${{ secrets.GH_USER }}

      - name: Build and push container image
        run: |
          docker build -f ./Dockerfile -t ghcr.io/markbolier/pdok-charting:latest .
          docker push ghcr.io/markbolier/pdok-charting:latest

      - name: Apply Kubernetes configuration
        run: |
          kubectl apply \
            -f kubernetes/namespace.tst.yaml \
            -f kubernetes/ingress.tst.yaml \
            -n testing

      - name: Verify deployment
        run: kubectl rollout status deployment/pdok-charting -n testing
